### ISSUE TITLE
More details about the experiment?

### ISSUE THREAD

**Issue by hlnull** [USC-GVL/Agent-Driver#1]
hi, thanks for the great work. 

I do agree the following descriptions. 
The language representations might be a better method for leveraging LLM in autonomous driving  
'''
The discrepancy between language and numerical representations poses a significant challenge to incorporating human experiential knowledge and reasoning capability into existing driving systems, thereby widening the chasm from genuine human driving performance.
''' 

By the way, I cannot find the appendix in the paper which makes reproducing the experiment difficult. Will it be possible to provide more details about the experiment?  Such as the number of GPU cards, etc. 

<img width="496" alt="image" src="https://github.com/USC-GVL/Agent-Driver/assets/25882690/2e7c4407-8299-4cb9-8548-c6149960dee2">

**Comment by WangYueFt** [comment]
Hi, 

We indeed provide supplement in the updated draft: https://arxiv.org/pdf/2311.10813.pdf. Have you checked it out?

Thanks,
Yue

**Comment by hlnull** [comment]
> Hi,
> 
> We indeed provide supplement in the updated draft: https://arxiv.org/pdf/2311.10813.pdf. Have you checked it out?
> 
> Thanks, Yue

Great. I did not find it is updated. 

Thanks for the reminder :).
