### ISSUE TITLE
When will the code be open source?

### ISSUE THREAD

**Issue by jimchenhub** [USC-GVL/Agent-Driver#2]
Thank you for your great work. I was wondering when the code will be open source?

**Comment by Krasjet-Yu** [comment]
I also wonder when the code will be open source ~

**Comment by keerheer** [comment]
Me too

**Comment by BillChan226** [comment]
Great job! I am also wondering when the code will be open source?

**Comment by PointsCoder** [comment]
@BillChan226 @jimchenhub @Krasjet-Yu @keerheer 
Code has been released for your reference
